site_name: Hecatomb
site_url: "https://github.com/shandley/hecatomb"
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - text
nav:
    - About Hecatomb: index.md
    - Installation: install.md
    - Usage: usage.md
    - Advanced: advanced.md
    - Tutorial: tutorial.md
    - FAQ: faq.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets