site_name: Hecatomb
site_url: "https://github.com/shandley/hecatomb"
theme: readthedocs
nav:
    - About Hecatomb: index.md
    - Installation: install.md
    - Usage: usage.md
    - Advanced: advanced.md
    - Tutorial: tutorial.md
    - FAQ: faq.md