#####################################################
## | |__   ___  ___ __ _| |_ ___  _ __ ___ | |__   ##
## | '_ \ / _ \/ __/ _` | __/ _ \| '_ ` _ \| '_ \  ##
## | | | |  __/ (_| (_| | || (_) | | | | | | |_) | ##
## |_| |_|\___|\___\__,_|\__\___/|_| |_| |_|_.__/  ##
#####################################################

# For more information see: https://github.com/shandley/hecatomb and https://hecatomb.readthedocs.io/en/latest/

---


##################
# Run Parameters #
##################

# !! check/change the following items !!
# Database installation location, leave blank = use hecatomb install location
Databases:

# Memory for MMSeqs in megabytes (e.g 64GB = 64000, recommend >= 64000)
MMSeqsMem: 64000
# Threads for MMSeqs (recommend >= 16)
MMSeqsCPU: 32
# Max runtime for MMSeqs
MMSeqsTimeMin: 5760  # 4 days

# Memory for BBTools in megabytes (recommend >= 16000)
BBToolsMem: 16000
# CPUs for BBTools (recommend >= 8)
BBToolsCPU: 8

# Memory for Megahit/Flye in megabytes (recommend >= 32000)
MhitMem: 32000
# CPUs for Megahit/Flye in megabytes (recommend >= 16)
MhitCPU: 16

# Memory for slightly RAM-hungry jobs in megabytes (recommend >= 16000)
MiscMem: 16000
# CPUs for slightly RAM-hungry jobs (recommend >= 2)
MiscCPU: 2


############################
# Optional Rule Parameters #
############################

# Preprocessing
QSCORE: 15 # Read quality trimming score (rule remove_low_quality in 01_preprocessing.smk)
READ_MINLENGTH: 90 # Minimum read length during QC steps (rule remove_low_quality in 01_preprocessing.smk)
CONTIG_MINLENGTH: 1000 # Read minimum length (rule contig_reformating_and_stats in 01_preprocessing.smk)
ENTROPY: 0.5 # Read minimum entropy (rule remove_low_quality in 01_preprocessing.smk)
ENTROPYWINDOW: 25 # entropy window for low qual read filter
CLUSTERID: 0.97 # Linclust read clustering percent identity (rule cluster_similar_sequences: in 01_preprocessing.smk)

# addHost settings
Entropy: 0.7


###################
# MMSeqs settings #
###################

# CUTOFFS
# --min-length should be < 1/3 of read_minlen, -e is max allowed e-value of alignments
filtAA:
 --min-length 30
 -e 1e-5
# --min-length for NT should be less than read_minlen
filtNT:
 --min-length 90
 -e 1e-5

# PERFORMANCE SETTINGS
# sensitive AA search
perfAA:
 --start-sens 1
 --sens-steps 3
 -s 7
 --lca-mode 2
 --shuffle 0

# fast AA search
perfAAfast:
 -s 4.0
 --lca-mode 1
 --shuffle 0

# sensitive NT search
perfNT:
 --start-sens 2
 -s 7
 --sens-steps 3

# fast NT search
perfNTfast:
 -s 4.0

# REQUIRED ADDITIONAL AA MMSEQS SETTINGS
# DON'T TOUCH THIS BIT IT WILL BREAK THE PIPELINE
reqAA:
 -a
 --tax-output-mode 2
 --search-type 2
 --tax-lineage 1
 --lca-ranks "superkingdom,phylum,class,order,family,genus,species"
 --format-output "query,target,evalue,pident,fident,nident,mismatch,qcov,tcov,qstart,qend,qlen,tstart,tend,tlen,alnlen,bits,qheader,theader,taxid,taxname,taxlineage"


#####################
# Database download #
#####################

# You shouldn't need to touch anything in this section

# Mirrors
mirror1: https://hecatombdatabases.s3.us-west-2.amazonaws.com/databases/
mirror2: https://htcf.wustl.edu/files/lXraB7eg/hecatomb/

# files to download or unpack
dbFiles:
 - contaminants/nebnext_adapters.fa
 - contaminants/primerB.fa
 - contaminants/rc_primerB_ad6.fa
 - contaminants/truseq.fa
 - contaminants/vector_contaminants.fa
 - aa/virus_primary_aa/sequenceDB
 - aa/virus_primary_aa/sequenceDB.dbtype
 - aa/virus_primary_aa/sequenceDB_delnodes.dmp
 - aa/virus_primary_aa/sequenceDB_h
 - aa/virus_primary_aa/sequenceDB_h.dbtype
 - aa/virus_primary_aa/sequenceDB_h.index
 - aa/virus_primary_aa/sequenceDB.index
 - aa/virus_primary_aa/sequenceDB.lookup
 - aa/virus_primary_aa/sequenceDB_mapping
 - aa/virus_primary_aa/sequenceDB_merged.dmp
 - aa/virus_primary_aa/sequenceDB_names.dmp
 - aa/virus_primary_aa/sequenceDB_nodes.dmp
 - aa/virus_primary_aa/sequenceDB.source
 - aa/virus_secondary_aa/sequenceDB
 - aa/virus_secondary_aa/sequenceDB.dbtype
 - aa/virus_secondary_aa/sequenceDB_delnodes.dmp
 - aa/virus_secondary_aa/sequenceDB_h
 - aa/virus_secondary_aa/sequenceDB_h.dbtype
 - aa/virus_secondary_aa/sequenceDB_h.index
 - aa/virus_secondary_aa/sequenceDB.index
 - aa/virus_secondary_aa/sequenceDB.lookup
 - aa/virus_secondary_aa/sequenceDB_mapping
 - aa/virus_secondary_aa/sequenceDB_merged.dmp
 - aa/virus_secondary_aa/sequenceDB_names.dmp
 - aa/virus_secondary_aa/sequenceDB_nodes.dmp
 - aa/virus_secondary_aa/sequenceDB.source
 - host/bat/masked_ref.fa.gz
 - host/camel/masked_ref.fa.gz
 - host/cat/masked_ref.fa.gz
 - host/celegans/masked_ref.fa.gz
 - host/cow/masked_ref.fa.gz
 - host/dog/masked_ref.fa.gz
 - host/human/masked_ref.fa.gz
 - host/macaque/masked_ref.fa.gz
 - host/mosquito/masked_ref.fa.gz
 - host/mouse/masked_ref.fa.gz
 - host/rat/masked_ref.fa.gz
 - host/tick/masked_ref.fa.gz
 - host/virus_shred.fasta.gz
 - nt/virus_primary_nt/sequenceDB
 - nt/virus_primary_nt/sequenceDB.dbtype
 - nt/virus_primary_nt/sequenceDB_h
 - nt/virus_primary_nt/sequenceDB_h.dbtype
 - nt/virus_primary_nt/sequenceDB_h.index
 - nt/virus_primary_nt/sequenceDB.index
 - nt/virus_primary_nt/sequenceDB.lookup
 - nt/virus_primary_nt/sequenceDB.source
 - nt/virus_secondary_nt/sequenceDB
 - nt/virus_secondary_nt/sequenceDB.dbtype
 - nt/virus_secondary_nt/sequenceDB_h
 - nt/virus_secondary_nt/sequenceDB_h.dbtype
 - nt/virus_secondary_nt/sequenceDB_h.index
 - nt/virus_secondary_nt/sequenceDB.index
 - nt/virus_secondary_nt/sequenceDB.lookup
 - nt/virus_secondary_nt/sequenceDB.source
 - tables/2020_07_27_Viral_classification_table_ICTV2019.txt
 - tables/phage_taxonomic_lineages_12102020.txt
 - tax/taxonomy/citations.dmp
 - tax/taxonomy/delnodes.dmp
 - tax/taxonomy/division.dmp
 - tax/taxonomy/gc.prt
 - tax/taxonomy/gencode.dmp
 - tax/taxonomy/merged.dmp
 - tax/taxonomy/names.dmp
 - tax/taxonomy/nodes.dmp
