---
Paths:
  # The Database directory is where to save the databases. 
  # You can install them using download_databases.snakefile 
 
  Databases: /mnt/data1/databases/hecatomb
  
  # Host directory name
  # e.g. human, mouse, dog, etc. Needs to be the name of the dir with the virus masked reference data

  Host: macaque

  # Temp is a temporary directory. By default we make 
  # subdirectories in here for each application

  Temp: tmp
 
  # The reads directory has your input fastq files that you want
  # to process through hecatomb

  Reads: /mnt/data1/databases/hecatomb/test_data

DatabaseFiles:
  # These are our predefined databases that we screen against, but you may want to replace host with e.g. mouse

  host: human_virus_masked.fasta
  contaminants: vector_contaminants.fa.gz

Output:
  # Directory where all files will be kept throughout the QC process
  
  QC: QC

  # Directory where results are stored

  Results: results

System:
  # How much memory you want to allocate to java (required for bbtools steps)
  
  Memory: -Xmx128g

Options:
  # These are options that control the flow of the pipeline and add additional
  # processing steps. Set these to True to include them or False to ignore them

  # run_prinseq first cleans the reads with prinseq++
  # run_prinseq: True

  # use_bowtie substitutes bowtie2 and samtools for bbmap
  # use_bowtie: True


