---
# !! You must check/change the following items !!
# Databases: (change to the path of your hecatomb databases)
# Host: (change to the name of the directory containing your masked host database)
# Reads: (change to the location of your projects input reads)
# System: Memory: Change to the max amount of memory used by bbtools (likely your max system memory)

Paths:
  # The Database directory is where to save the databases. 
  # You can install them using download_databases.snakefile 
 
  Databases: /mnt/data1/databases/hecatomb
  
  # Host directory name
  # e.g. human, mouse, dog, etc. Needs to be the name of the directory with the virus masked reference data

  Host: macaque

  # Temp is a temporary directory. By default we make 
  # subdirectories in here for each application

  Temp: tmp
 
  # The reads directory has your input fastq files

  Reads: /mnt/data1/databases/hecatomb/test_data/raw_data/subsampled
  
System:
  # How much memory you want to allocate to java (required for bbtools steps)
  
  Memory: -Xmx128g

DatabaseFiles:
  # These are our predefined databases that we screen against, but you may want to replace host with e.g. mouse

  host: human_virus_masked.fasta

Output:
  QC: CLEANED
  STATS: STATS
  LOGS: LOGS
  RESULTS: RESULTS

### Additional tuning parameters ###
### Advise not to change and keep default, but included here for fine-tuning to ones own dataset ###

# contaminant_removal.smk rule optional parameters
QSCORE: 35
MINLENGTH: 100
  
